version: '3.8'

services:
  app:
    image:  rohinitibile/institutesystem:1.0.0
    ports:
      - 8080:8080
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/localspringbootdb?autoReconncet=true&SSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root@123
      
    depends_on:
     - db
  db:
    image: mysql:8.0.20
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localspringdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root@123
    
 
     
    
    
